services:
  api_a:
    build: .
    ports:
      - "8881:8880"
    environment:
      WS_PORT: "8881"
      WS_HOST: "localhost"
    depends_on:
      redis:
        condition: service_started
  api_b:
    build: .
    ports:
      - "8882:8880"
    environment:
      WS_PORT: "8882"
      WS_HOST: "localhost"
    depends_on:
      redis:
        condition: service_started
  proxy:
    image: "nginx:1.27"
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      api_a:
        condition: service_started
      api_b:
        condition: service_started
  redis:
    image: "redis:7.4"
    command: "redis-server --save ''"
